name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Atualiza todo dia Ã  meia-noite
  workflow_dispatch: # Permite rodar manualmente
push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: HSThzz
          template: classic
          base: header, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          theme: tokyonight
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
